### ISSUE TITLE
Missing are: stock-db.sql & db.php

### ISSUE THREAD

**Issue by offternet** [aftechro/inventory-stock-management#1]
Unable to find stock-db.sql & db.php in your project as stated in readmen so I can properly connect to mysql database. Any help is appreciated. TIA cpumore@yahoo.com

**Comment by aftechro** [comment]
Apologies, uploaded now!

**Comment by offternet** [comment]
**RESOLVED with your new update.**
Thank You for your help. used your update files to access program. One Additional error: Missing "stock_logs" table in Database: 
Error - generated: 
"Fatal error: Uncaught mysqli_sql_exception: Table 'yadgui36_inventory2.stock_logs' doesn't exist in /home4/yadgui36/jacksbackyardsales.com/inventory2/dashboard.php:286 Stack trace: #0 /home4/yadgui36/jacksbackyardsales.com/inventory2/dashboard.php(286): mysqli->query('\n ...') #1 {main} thrown in /home4/yadgui36/jacksbackyardsales.com/inventory2/dashboard.php on line 286"

**Comment by offternet** [comment]
Additionally, (No rush on my end & appreciate your assistance very much), I do not see complete menu items. See attached screenshot image
![screenshot-error-menu-less](https://github.com/user-attachments/assets/0b28873c-7712-43b7-8914-7e27b5384c47)

**Comment by aftechro** [comment]
Just done another export, with updated version

**Comment by aftechro** [comment]
make sure you also set your role as admin in php my admin, from your screenshot i see your menu missing

![image](https://github.com/user-attachments/assets/47a8f80a-5371-403d-b527-2fbe59faf16a)

**Comment by aftechro** [comment]
Dont forget to set your username as admin role
![image](https://github.com/user-attachments/assets/6786b83c-92d6-4893-b8d6-24432ecd6b18)

**Comment by offternet** [comment]
RESOLVED: set role to "admin" (Learned many things with your help) THANK YOU !
> Dont forget to set your username as admin role ![image](https://private-user-images.githubusercontent.com/38830718/376248242-6786b83c-92d6-4893-b8d6-24432ecd6b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTIyNjgsIm5iZiI6MTcyODkxMTk2OCwicGF0aCI6Ii8zODgzMDcxOC8zNzYyNDgyNDItNjc4NmI4M2MtOTJkNi00ODkzLWI4ZDYtMjQ0MzJlY2Q2YjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEzMTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDllY2M0YTE2NGM1ODJkMWQ4NmRiY2M0NDFhMzJkZjgyNTk2N2FkNmI5YWQyZGRlYzdkZDkxMzEwNzEzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JEjCrqzQLBYN1R1balAmd4Sm5jXkFO8-ikPxcMhER-Y)

**Comment by offternet** [comment]
I will be testing your program all day. I really like the layout and options. Thanks again for your help. I have funds for assistance in customizing your inventory to a specific industry if you are interested. Please email about it. Thanks, Robert Cooper, Kansas, USA  (Retired)

**Comment by aftechro** [comment]
Happy days. Still bits to do, email alerts for low stock and out of stock

i done the app/quote.php which i`m using with my ticketing system, but handy for you if you wanna quote someone, you can copy the table in email :d

**Comment by aftechro** [comment]
> I will be testing your program all day. I really like the layout and options. Thanks again for your help. I have funds for assistance in customizing your inventory to a specific industry if you are interested. Please email about it. Thanks, Robert Cooper, Kansas, USA (Retired)

Appreciate that. i may do a paypal donations or something. will keep in mind :d

**Comment by aftechro** [comment]
you are missing as well the fontawesome, you have to read the file: https://github.com/aftechro/inventory-stock-management/blob/main/assets/IMPORTANT-README.txt

download and extract the files into assets folder

**Comment by offternet** [comment]
**RESOLVED** Installed fontawesome.
> you are missing as well the fontawesome, you have to read the file: https://github.com/aftechro/inventory-stock-management/blob/main/assets/IMPORTANT-README.txt
> 
> download and extract the files into assets folder

**Comment by offternet** [comment]
Product Description is **printed twice in Product Management display**. Okay on Stock Management Display. Okay in Product table in Database.
![duplicate-product-description](https://github.com/user-attachments/assets/ddab9b7d-66c6-48c4-81a6-7882a0a295f4)

**Comment by aftechro** [comment]
good catch. remove `<?= htmlspecialchars($product['description']) ?>` from line 314 so from this

` <td><?= html_entity_decode($product['description']) ?><?= htmlspecialchars($product['description']) ?></td>`
 will be this:
 ` <td><?= html_entity_decode($product['description']) ?>`
  
  as well, i can see your fontawesome not loading, the icons are not showing on your menu. make sure you have them downloaded inside assets and rename folder as fontawesome

**Comment by offternet** [comment]
> as well, i can see your fontawesome not loading, the icons are not showing on your menu. make sure you have them downloaded inside assets and rename folder as fontawesome

Issue Remains: **No Icons in Menu** I have downloaded fontawesome folder inside assets folder; still NO Icons on menu. 
 --Debug--> I tested with 3 different browsers; No Fawesome Icons (So not a cache issue)
          --?--> Could it be I am missing a php library (or php setting)  in my hosting setup <--?--
     --Info--> I use Hostgator Shared Hosting <--info-- 
         --?--> Should I try and reinstall Fontawesome again <--?--

--Info--> I have printed out all code of your project to learn more about it <--Info--

**Comment by aftechro** [comment]
> > as well, i can see your fontawesome not loading, the icons are not showing on your menu. make sure you have them downloaded inside assets and rename folder as fontawesome
> 
> Issue Remains: **No Icons in Menu** I have downloaded fontawesome folder inside assets folder; still NO Icons on menu. --Debug--> I tested with 3 different browsers; No Fawesome Icons (So not a cache issue) --?--> Could it be I am missing a php library (or php setting) in my hosting setup <--?-- --Info--> I use Hostgator Shared Hosting <--info-- --?--> Should I try and reinstall Fontawesome again <--?--
> 
> --Info--> I have printed out all code of your project to learn more about it <--Info--

check if you have header.php 
i sent you an email earlier, reply to it and i`ll assist you remotely, as i may need you to give me access to your hosting

**Comment by offternet** [comment]
> > Issue Remains: **No Icons in Menu** 
> 
> check if you have header.php i sent you an email earlier, reply to it and i`ll assist you remotely, as i may need you to give me access to your hosting. 

----- 
Will check the header.php file.

**Comment by offternet** [comment]
RESOLVED
