### ISSUE TITLE
Password Rejected by mysql server - double quotes not accepted - Resolved

### ISSUE THREAD

**Issue by offternet** [aftechro/inventory-stock-management#3]
Error: **Password rejected by mysql-database.**
file: **db.php**
line: 4

Reason: Isolated Incident - use of double quotes rejected by shared hosting mysql database
Server: Mysql 5.x
OS: Linux

Resolved by:  **using single quote around password**.

**Comment by aftechro** [comment]
hmm, that`s strange. good you sorted out
