### ISSUE TITLE
Product Page: Delete button non-fuctional

### ISSUE THREAD

**Issue by offternet** [aftechro/inventory-stock-management#4]
Delete button for product non-fuctional

file: products.php
**Add Product** - works
Actions --> **Edit**  - works
Actions --> **Delete** - **no action when clicked**

Verified with new installation of current complete code and Re-Produced Error.

Record(s) can be deleted manully in database "products table" resulting in record being removed from products page.

**Comment by aftechro** [comment]
strange, just noticed it too. is just some scripts needs to be called before the script runs, so while most of the js scripts are in the footer php, that wont work, so i moved them in the header.php

removed them from the footer.php and added them to header.php instead

    
    <script src="assets/js/jquery-3.6.0.min.js"></script>
    <script src="assets/js/jquery-ui.min.js"></script>
    <script src="assets/js/popper.min.js"></script>

**Comment by offternet** [comment]
Thank you for explaination. Moved below Scripts to header.php and now Product "Delete" is working.

```
<!-- Scripts moved from footer.php -->
<script src="assets/js/jquery-3.6.0.min.js"></script>
<script src="assets/js/jquery-ui.min.js"></script>
<script src="assets/js/popper.min.js"></script>
```
